### ISSUE TITLE
Doubt about stop List.Generate in Text.ContainsAny 

### ISSUE THREAD

**Issue by wanderleihuttel** [tycho01/pquery#32]
Hello I've made a little modification in the function "Text.ContainsAny" to get a index from a list.

My doubt is how could I stop the List.Generate when I found a true value in "Text.Contains(str,needles{[i]})" ?

````
//Text.ContainsAny
(str, needles) as any =>
let
  needles = List.Buffer(needles),
  count = List.Count(needles),
  break = 0
in
  let
    idx = 
    List.PositionOf(
      List.Generate(
        ()=>[i=0],
        each [i] < count,
        each [i=[i]+1],
        each Text.Contains(str,needles{[i]})
      ),
      true
    ),
    output = if idx < 0 then null else needles{idx}
  in
    output
````

**Comment by KiaraGrouwstra** [comment]
hey! so MS has docs on this function [here](https://docs.microsoft.com/en-us/powerquery-m/list-generate).

the argument you'd wanna change in this case is the second one, containing the 'continue' condition -- instead of only checking `[i]`, you'd also want to check an additional value of your record.

as you may notice from this repo I haven't done PowerQuery in a while, but I think that'd involve like a `&&` to combine the conditions. I think that would also change the function syntax from the `each` syntax sugar to a plain [`function-expression`](https://docs.microsoft.com/en-us/powerquery-m/m-spec-consolidated-grammar).

furthermore, you'd then need to change the third argument to actually store your calculated 'contains' value.

does that sorta help to get you back on track?

**Comment by wanderleihuttel** [comment]
Hello @tycho01 !

In fact I'm a bit newbie in list functions.

But you gave me some light that I've could did resolved it! 
I've modified the line of increment of [i] to check if found or not.

Thanks so much! =)
````
(str, needles) as any =>
let
	needles = List.Buffer(needles),
	count = List.Count(needles),
	achou = false,
	idx = 
	List.PositionOf(
		List.Generate(
			()=>[i=0],
			each [i] < count,
			each [i=if Text.Contains(str,needles{[i]}) = false then [i]+1 else count],
			each Text.Contains(str,needles{[i]})
		),
		true
	),
	output = if idx < 0 then null else needles{idx}
in
	output
````

**Comment by KiaraGrouwstra** [comment]
haha nice -- congratulations! :raised_hands: :tada:
